version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: widen
  ignore:
  - dependency-name: yalc
    versions:
    - 1.0.0-pre.50
    - 1.0.0-pre.51
    - 1.0.0-pre.52
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: liquidjs
    versions:
    - 9.20.1
    - 9.22.0
    - 9.22.1
    - 9.23.0
    - 9.23.1
    - 9.23.2
    - 9.23.3
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: mustache
    versions:
    - 4.1.0
