GET http://localhost:3000/post/4
Content-Type: application/json

###
GET http://localhost:3000/post
Content-Type: application/json

###

POST http://localhost:3000/post
Content-Type: application/json

{
    "title": "title - nehhw555",
    "name": "name - new11",
    "description": "description - new33",
    "image": "image - new22"
}

###

PUT http://localhost:3000/post/15
Content-Type: application/json

{
    "title": "title - nehffhw555",
    "name": "name - new11",
    "description": "description - new33",
    "image": "image - new22"
}